model:
  name: simplecnn
  hparams:
    mlp_hidden_sizes: [512, 256]
    mlp_activation: [relu, relu]
    dropout_rate: 0
    lstm_hidden_sizes: [256, 256]
    lstm_dropout: 0
    bidirectional: false
    readout: last
    use_ln: false
    conv_channels: [64, 128, 256]
    conv_activation: [relu, relu, relu]
    kernel_size: 8
    padding: 1
    pool: adaptive_avg
    pool_k: 16
    use_bn: false
    output_activation: linear
    n_layers: 2
  search: {}

trainer:
  hparams:
    epochs: 7
    batch_size: 512
    torch_patience: 10
    min_delta: 1e-10
    optuna_patience: 3
    loss: mse
    metrics: [mae, mse, dir_acc, qlike]
    val_every: 1
    optimizer_type: sgd
  search:
    weight_decay:
      type: float
      low: 1e-06
      high: 1
      log: false
    lr:
      type: float
      low: 1e-05
      high: 0.1
      log: false

walkforward:
  target_col: var
  lookback: 0
  ratio_train: 3
  ratio_val: 1
  ratio_test: 1
  step: 1257
  lags: 100
  max_folds: null
  min_folds: null
  scale: true
  annualize: true
  scale_type: logstandard
  clip: 0.1

experiment:
  name: cnn_100_sgd_v2
  hyperparams_search: true
  monitor: val_loss
  mode: min
  type: volatility
  n_trials: 25
  merge_train_val: false

data:
  df_path: null
  df_master: null
