experiment:
  name: "mlp_40"
  type: "volatility"
  random_state: 1234
  monitor: "val_loss"
  mode: "min"
  hyperparams_search: False

# this whole thing might be useless
data: 
  # df_path: "data/sp500_daily_data.parquet" # if left out the pipeline takes it automatically
  df_master:  # if left out the pipeline takes it automatically

walkforward:
  target_col: var
  lookback: 5  
  max_folds: 
  step: 251
  ratio_train: 3
  ratio_val: 1
  ratio_test: 1
  lags: 40
  scale: True
  #purge_days: 20
  #embargo_days: 20

trainer:
  hparams:
    epochs: 250
    batch_size: 512 # P. said 256-512 to "kill some noise"
    torch_patience: 
    min_delta: 1e-4  
    optuna_patience: 200  
    lr: 1e-4
    loss: "mse"
    metrics: ["mae","mse", "dir_acc"]
    weight_decay: 0
    val_every: 1
    #search: False

model:
  name: "mlp"
  hparams:  
    hidden_sizes: [512, 256, 256, 128] 
    dropout_rate: 0
    activation: [relu, relu, relu, relu]
    output_activation: linear
    conv_channels: [32]
    use_bn: False
    kernel_size: 3
    padding: 3
    pool: adaptive_avg
    pool_k: 1

