experiment:
  name: "pippo_6layers_no_dropoutl2"
  type: "price_prediction"
  random_state: 1234
  #output_root: "experiments"
  monitor: "val_loss"
  mode: "min"
  hyperparams_search: False

data:
  # df_path: "data/sp500_daily_data.parquet" # if left out the pipeline takes it automatically
  target_col: "y"
  feature_cols: ['feature_0', 'feature_1', 'feature_2', 'feature_3', 'feature_4',
        'feature_5', 'feature_6', 'feature_7', 'feature_8', 'feature_9',
        'feature_10', 'feature_11', 'feature_12', 'feature_13', 'feature_14',
        'feature_15', 'feature_16', 'feature_17', 'feature_18', 'feature_19']
  standardize: true
  per_asset_norm: true

walkforward:
  max_folds: 
  step: 251
  ratio_train: 3
  ratio_val: 1
  ratio_test: 1
  lags: 20
  #purge_days: 20
  #embargo_days: 20

trainer:
  hparams:
    epochs: 50
    batch_size: 512 # P. said 256-512 to "kill some noise"
    lr: 1.0e-3
    loss: "mse"
    metrics: ["mae","mse", "dir_acc"]
    weight_decay: 0
    val_every: 1
    search: False

model:
  name: "mlp"
  hparams:  
    hidden_sizes: [1024, 1024, 1024, 1024, 1024, 1024] 
    dropout_rate: 0 
    activation: [relu, relu, relu, relu, relu, relu]
    output_activation: linear
    learning_rate: 0.001
