experiment:
  name: "mlp"
  type: "price_prediction"
  seed: 1234
  output_root: "experiments"
  monitor: "val_loss"
  mode: "min"

data:
  # df_path: "data/sp500_daily_data.parquet" # if left out the pipeline takes it automatically
  target_col: "y"
  feature_cols: ['feature_0', 'feature_1', 'feature_2', 'feature_3', 'feature_4',
        'feature_5', 'feature_6', 'feature_7', 'feature_8', 'feature_9',
        'feature_10', 'feature_11', 'feature_12', 'feature_13', 'feature_14',
        'feature_15', 'feature_16', 'feature_17', 'feature_18', 'feature_19']
  standardize: true
  per_asset_norm: true

walkforward:
  max_folds: 
  step: 251
  ratio_train: 3
  ratio_val: 1
  ratio_test: 1
  lags: 20
  #purge_days: 20
  #embargo_days: 20

trainer:
  epochs: 50
  batch_size: 128
  lr: 1.0e-3
  loss: "mse"
  metrics: ["mae","mse"]
  search: False

model:
  name: "mlp"
  hparams:  
    hidden_sizes: [32, 32] 
    dropout_rate: 0.2 
    activation: relu
    l2_reg: 0.001
    output_activation:
