"model": 
    "name": "mlp"
    "hparams": 
        "mlp_hidden_sizes": [
            512,
            256,
            256,
            128
        ]
        "mlp_activation": [
            "relu",
            "relu",
            "relu",
            "relu"
        ]
        "conv_activation": [
            "relu",
            "relu",
            "relu"
        ]
        "output_activation": "linear"
        "conv_channels": [
            64,
            128,
            256
        ]
        "use_bn": false
        "kernel_size": 3
        "padding": 1
        "pool": "adaptive_max"
        "pool_k": 4
        "dropout_rate": 0

"trainer": 
    "hparams": 
        "epochs": 250
        "batch_size": 512
        "torch_patience": 75
        "min_delta": "1e-10"
        "optuna_patience": 25
        "loss": "mse"
        "metrics": [
            "mae",
            "mse",
            "dir_acc",
            "qlike"
        ]
        "val_every": 1
        "lr": "1e-4"
        "weight_decay": "1e-5"
    

"walkforward": 
    "target_col": "ret"
    "lookback": 0
    "ratio_train": 3
    "ratio_val": 1
    "ratio_test": 1
    "step": 251
    "lags": 40
    "max_folds": null
    "scale": true
    "clip": false

"experiment": 
    "name": "mlp_40"
    "hyperparams_search": false
    "monitor": "val_loss"
    "mode": "min"
    "type": "price_prediction"
    "n_trials": 10
    "random_state": 42
"data": 
    "df_master": null
