experiment:
  name: "mlp_504"
  type: "price_prediction"
  random_state: 1234
  monitor: "val_loss"
  mode: "min"
  n_trials: 10 # for random search 
  random_state: 42 # for reproducibility
  hyperparams_search: False

# this whole thing might be useless
data: 
  # df_path: "data/sp500_daily_data.parquet" # if left out the pipeline takes it automatically
  df_master:  # if left out the pipeline takes it automatically

walkforward:
  target_col: ret
  lookback: 0
  max_folds: 
  step: 1256
  ratio_train: 3
  ratio_val: 1
  ratio_test: 1
  lags: 504
  scale: True
  clip: False
  #purge_days: 20
  #embargo_days: 20

trainer:
  hparams:
    epochs: 500
    batch_size: 512 # P. said 256-512 to "kill some noise"
    torch_patience: 75 # if empty early stopping is not active
    min_delta: 1e-10 # very small when not startdadized 
    optuna_patience: 25  
    loss: "mse"
    metrics: ["mae","mse", "dir_acc", "qlike"]
    val_every: 1
    lr: 5e-3
    weight_decay:  3e-3 # change to zero


model:
  name: "mlp"
  hparams:  
    hidden_sizes: [512, 256, 256, 128] 
    activation: [relu, relu, relu, relu]
    output_activation: linear
    conv_channels: [64, 128, 256]
    use_bn: False
    kernel_size: 3
    padding: 1
    pool: adaptive_max
    pool_k: 4
    dropout_rate: 0
 

